### ISSUE TITLE
KnockoutUpdate.php doesn't work?

### ISSUE THREAD

**Issue by Gajack33** [zhengfen/worldcup2018#2]
> php artisan db:seed --class="KnockoutUpdate.php"

ReflectionException  : Class KnockoutUpdate.php does not exist at C:\xampp\htdocs\coupe3\vendor\laravel\framework\src\Illuminate\Container\Container.php:767
    763|         if ($concrete instanceof Closure) {
    764|             return $concrete($this, $this->getLastParameterOverride());
    765|         }
    766|
    767|         $reflector = new ReflectionClass($concrete);
    768|
    769|         // If the type is not instantiable, the developer is attempting to resolve
    770|         // an abstract type such as an Interface of Abstract Class and there is
    771|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("KnockoutUpdate.php")
      C:\xampp\htdocs\coupe3\vendor\laravel\framework\src\Illuminate\Container\Container.php:767

  2   Illuminate\Container\Container::build("KnockoutUpdate.php")
      C:\xampp\htdocs\coupe3\vendor\laravel\framework\src\Illuminate\Container\Container.php:646

help?

**Comment by zhengfen** [comment]
php artisan db:seed --class=KnockoutUpdate
